// data.ts
export const reels = [
  {
    id: 1,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753594909/Nahi_hai_rgfqb4.mp4",
    username: "waleedahmad_09",
    description: "If I make it, it's not me, Allah. It's all You. #AllGloryToAllah",
    likes: "1.2M",
    shares: "100K",
    bookmarks: "80K",
  },
  {
    id: 2,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753605310/To_all_the_Elder_brothers_working_out_there_is_this_relatable_Join_us_now_www.w4work.com_c_q1op4u.mp4",
    username: "strongbrother",
    description: "Respect to the big bros holding it down. 💪 #AlphaMindset",
    likes: "854K",
    shares: "59K",
    bookmarks: "38K",
  },
  {
    id: 3,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753544257/SnapInsta.to_AQNsiz5zh2reOSNKPpkYjl7EFNtnU908osoOTEoX10n-RK5xo2XQn6ByjOTquo3_pLNn9BAJCes0J868i0-7BsfLfb6h7FdRt8HS1Cg_rweahk.mp4",
    username: "creative_mindset",
    description: "Create like it’s your last day alive. 🎨🔥",
    likes: "720K",
    shares: "80K",
    bookmarks: "65K",
  },
  {
    id: 4,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753594908/Telegram_link_in_bio_Flw_-_relatable_trader__trader_reel_viral_atrader_lovetrade_dhvk35.mp4",
    username: "market_wolf",
    description: "Telegram link in bio 📈💸",
    likes: "540K",
    shares: "60K",
    bookmarks: "41K",
  },
  {
    id: 5,
    src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    username: "naturelover",
    description: "Sometimes you gotta escape to find peace 🌄",
    likes: "230K",
    shares: "20K",
    bookmarks: "18K",
  },
  {
    id: 6,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753594908/Relax_and_just_keep_going_%EF%B8%8FWarren_Buffett-_The_Oracle_of_Omaha_and_Master_of_Value_InvestingWarr_vyiizc.mp4",
    username: "wealthmind",
    description: "Relax and just keep going. Warren knows. 💼",
    likes: "610K",
    shares: "70K",
    bookmarks: "58K",
  },
  {
    id: 7,
    src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    username: "animationking",
    description: "Classic never dies 🐰🎥",
    likes: "920K",
    shares: "110K",
    bookmarks: "75K",
  },
  {
    id: 8,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753594683/Raise_your_hands_not_just_in_need_but_in_Shukr_for_all_that_Allah_has_already_given.For_every_mpovgq.mp4",
    username: "thankful_heart",
    description: "Shukr changes everything 🤲🏼",
    likes: "1.5M",
    shares: "150K",
    bookmarks: "120K",
  },
  {
    id: 9,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753605305/Why_settle_for_average_when_greatness_runs_in_your_veins_Be_the_legacy_your_bloodline_remem_jgcohz.mp4",
    username: "legacybuilder",
    description: "You were born for greatness 💥",
    likes: "870K",
    shares: "97K",
    bookmarks: "83K",
  },
  {
    id: 10,
    src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    username: "dramaqueen",
    description: "For those bigger meltdowns 😂",
    likes: "310K",
    shares: "28K",
    bookmarks: "19K",
  },
  {
    id: 11,
    src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    username: "road_ranger",
    description: "Street or dirt, just go. 🚙💨",
    likes: "460K",
    shares: "42K",
    bookmarks: "36K",
  },
  {
    id: 12,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753594911/Weather_%EF%B8%8F_-_viral_stockmarket_trader_tourism_mount_rain_zccn6i.mp4",
    username: "stormhunter",
    description: "Weather the storm ☔️⚡️",
    likes: "510K",
    shares: "45K",
    bookmarks: "40K",
  },
  {
    id: 13,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753594684/I_was_in_such_a_hurry_to_grow_up_I_didn_t_know_what_I_was_leaving_behind_%EF%B8%8F_Baarish_me_mummy_xzw9ts.mp4",
    username: "nostalgia_zone",
    description: "I miss the rain and childhood… ☔️❤️",
    likes: "1.1M",
    shares: "98K",
    bookmarks: "91K",
  },
  {
    id: 14,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753605308/I_realized-_no_situation_is_permanent._And_no_failure_defines_me.I_used_to_think_some_situations_wzxtcs.mp4",
    username: "growthmindset",
    description: "Nothing is permanent — keep growing 🌱",
    likes: "670K",
    shares: "75K",
    bookmarks: "52K",
  },
  {
    id: 15,
    src: "https://res.cloudinary.com/dejxlghwu/video/upload/v1753605305/If_I_make_it_it_s_not_me_God._It_s_all_You._AllGloryToGod_godgetscredit_faithjourney_godisg_yctcdh.mp4",
    username: "faithwalker",
    description: "It’s all You, God 🙏 #Faith",
    likes: "1.8M",
    shares: "160K",
    bookmarks: "140K",
  },
];
